In [ ]:
sample_dict={1:"apple",2:35.4,3:"data",2:"every",6:35.4,7:35.4,2:"hi"}
sample_dict

{1: 'apple', 2: 'hi', 3: 'data', 6: 35.4, 7: 35.4}

In [ ]:
sample_dict[1]

'apple'

In [ ]:
sample_dict[2]

'hi'

In [ ]:
sample_dict[3]

'data'

In [ ]:
sample_dict[6]

35.4

In [ ]:
sample_dict[7]

35.4

In [131]:
sample_dict["apple"]

KeyError: ignored

In [ ]:
sample_dict[7]=109

In [ ]:
sample_dict

{1: 'apple', 2: 'hi', 3: 'data', 6: 35.4, 7: 109}

In [ ]:
sample_dict[10]="Business"

new number add and add to list new name
and add new value output last

In [ ]:
sample_dict

{1: 'apple', 2: 'hi', 3: 'data', 6: 35.4, 7: 109, 10: 'Business'}

In [ ]:
sample_dict[11]="Sonu"

In [ ]:
sample_dict

{1: 'apple', 2: 'hi', 3: 'data', 6: 35.4, 7: 109, 10: 'Business', 11: 'Sonu'}

In [ ]:
sample_dict[3]

'data'

In [ ]:
sample_dict[4]="vedang"

In [ ]:
sample_dict

{1: 'apple',
 2: 'hi',
 3: 'data',
 6: 35.4,
 7: 109,
 10: 'Business',
 11: 'Sonu',
 4: 'vedang'}

new value add in last

### **#Numpy:Package for Multidimensional** 

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]] 
sample_matrix=np.array(list_of_lists)

In [ ]:
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# Create an array of zeros with 2 rows and 10 columns

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(3,2)

array([[0.51151482, 0.66976779],
       [0.98424047, 0.66704972],
       [0.31723457, 0.91527381]])

In [ ]:
np.random.rand(3,2)

In [ ]:
np.random.rand(3,2)

array([[0.18123766, 0.14169099],
       [0.61903218, 0.89146276],
       [0.02676688, 0.05030147]])

In [ ]:
np.random.randn(3,2)

array([[-0.76835977, -0.77753721],
       [-0.19900477,  0.0607646 ],
       [-1.02093707, -0.76589692]])

In [ ]:
np.random.randint(1,5)

1

In [ ]:
np.random.randint(34,100,50)

array([51, 79, 64, 69, 72, 93, 92, 58, 41, 38, 43, 37, 66, 87, 50, 84, 56,
       82, 41, 97, 68, 72, 95, 58, 90, 98, 57, 91, 65, 72, 47, 36, 35, 68,
       82, 83, 96, 84, 93, 73, 94, 69, 75, 79, 34, 84, 70, 79, 55, 35])

In [ ]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
rand_array=np.random.randint(0,100,20)
rand_array

array([61, 64, 71, 23, 90, 49, 45,  3, 84, 50, 87, 30, 52, 87, 88, 93, 56,
       39,  9, 89])

In [ ]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
rand_array.min()

3

In [ ]:
rand_array.argmin()

7

In [ ]:
sample_array.dtype

dtype('int64')

In [ ]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a=np.random.rand(2,3)
a

array([[0.4304556 , 0.67671472, 0.96878823],
       [0.96784149, 0.33607403, 0.14990184]])

In [ ]:
a.T

array([[0.4304556 , 0.96784149],
       [0.67671472, 0.33607403],
       [0.96878823, 0.14990184]])

In [ ]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
sample_array[3]

13

In [ ]:
sample_array[3:7]

array([13, 14, 15, 16])

In [ ]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [ ]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [137]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [138]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [140]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [141]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# **# Two-Dimensional array **

In [142]:
import numpy as np

In [143]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [144]:
sample_matrix[0:2,2]

array([ 1, 21])

In [145]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [146]:
sample_matrix[2]

array([56, 76, 24,  7])

In [148]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [149]:
sample_array=np.arange(1,20)

In [150]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [151]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [152]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [153]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [154]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [155]:
np.max(sample_array)

19

In [156]:
np.min(sample_array)

1

In [157]:
np.argmax(sample_array)

18

In [158]:
np.argmin(sample_array)

0

In [159]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [160]:
np.std(sample_array)

5.477225575051661

In [161]:
np.var(sample_array)

30.0

In [162]:
np.mean(sample_array)

10.0

In [163]:
array=np.random.randn(3,4)
array

array([[-0.25626863, -0.65757765,  0.57929227, -2.42292654],
       [ 0.98304296, -0.40456733, -1.33014601,  1.04685302],
       [-1.57393001, -0.16419099,  1.18107298,  1.56478643]])

In [165]:
np.round(array,decimals=3)

array([[-0.256, -0.658,  0.579, -2.423],
       [ 0.983, -0.405, -1.33 ,  1.047],
       [-1.574, -0.164,  1.181,  1.565]])

In [166]:
sports=np.array(['golf','cricket','fball','cricket','fball','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')